pokemonWebProject/pokemonWebProject/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pokemonWebProject.DAL;
using pokemonWebProject.Models;
using Microsoft.AspNet.Identity;
using pokemonWebProject.Models.pokemonModels;
using Microsoft.Owin.Security;

namespace pokemonWebProject.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationUsers
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var applicationUsers = db.Users.Include(a => a.Leader).Include(a => a.Professor).Include(a => a.Trainer);
            return View(applicationUsers.ToList());
        }

        // GET: ApplicationUsers/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.Leaders, "LeaderID", "Specialisation", applicationUser.Id);
            ViewBag.Id = new SelectList(db.Professors, "ProfessorID", "Specialisation", applicationUser.Id);
            ViewBag.Id = new SelectList(db.Trainers, "TrainerID", "TrainerID", applicationUser.Id);
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,FirstName,SecondName,DateOfBirth,Money,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Leaders, "LeaderID", "Specialisation", applicationUser.Id);
            ViewBag.Id = new SelectList(db.Professors, "ProfessorID", "Specialisation", applicationUser.Id);
            ViewBag.Id = new SelectList(db.Trainers, "TrainerID", "TrainerID", applicationUser.Id);
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);

            Trainer trainer = db.Trainers.Find(id);
            Leader leader = db.Leaders.Find(id);

            if (trainer != null)
            {
                db.Trainers.Remove(trainer);
            }
            if (leader != null)
            {
                db.Leaders.Remove(leader);
            }

            var challenge = db.Challenges.Where(x => x.CurrentTrainerID == id).ToList();
            foreach (var ch in challenge)
            {
                db.Challenges.Remove(ch);
            }

            int currentUserId = Int32.Parse(User.Identity.GetUserId());

            if (currentUserId == id)
            {
                AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                return RedirectToAction("Index", "Home");
            }

            db.Users.Remove(applicationUser);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}
 

pokemonWebProject/pokemonWebProject/Controllers/LeadersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using pokemonWebProject.DAL;
using pokemonWebProject.Models.pokemonModels;

namespace pokemonWebProject.Controllers
{
    public class LeadersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        // GET: Leaders
        [Authorize(Roles = "Admin, Trainer")]
        
        public ActionResult Index()
        {
            var leaders = db.Leaders.Include(l => l.Person);
            return View(leaders.ToList());
        }

        // GET: Leaders/Details/5
        [Authorize(Roles = "Admin, Trainer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Leader leader = db.Leaders.Include(p => p.Person).SingleOrDefault(x => x.LeaderID == id);
           
            if (leader == null)
            {
                return HttpNotFound();
            }
            return View(leader);
        }

        // GET: Leaders/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Leaders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "LeaderID,Specialisation,SecondJob,Sallary,PersonID")] Leader leader)
        {
            if (ModelState.IsValid)
            {
                db.Leaders.Add(leader);

                if (UserManager.GetRoles(leader.LeaderID) != null)
                {
                    if (UserManager.GetRoles(leader.LeaderID).Contains("Trainer"))
                    {
                        Trainer trainer = db.Trainers.Find(leader.LeaderID);
                        UserManager.RemoveFromRole(trainer.TrainerID, "Trainer");
                        db.Trainers.Remove(trainer);

                        var challenge = db.Challenges.Where(x => x.CurrentTrainerID == leader.LeaderID).ToList();
                        foreach (var ch in challenge)
                        {
                            db.Challenges.Remove(ch);
                        }
                    }
                }

                UserManager.AddToRole(leader.LeaderID, "Leader");

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // GET: Leaders/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leader leader = db.Leaders.Find(id);
            if (leader == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // POST: Leaders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "LeaderID,Specialisation,SecondJob,Sallary,PersonID")] Leader leader)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leader).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // GET: Leaders/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leader leader = db.Leaders.Include(p => p.Person).SingleOrDefault(x => x.LeaderID == id);

            if (leader == null)
            {
                return HttpNotFound();
            }
            return View(leader);
        }

        // POST: Leaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Leader leader = db.Leaders.Find(id);
            UserManager.RemoveFromRole(leader.LeaderID, "Leader");
            db.Leaders.Remove(leader);

            // Remove all challnges connected
            var challenge = db.Challenges.Where(x => x.CurrentTrainerID == id).ToList();
            foreach (var ch in challenge)
            {
                db.Challenges.Remove(ch);
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

    }
}

pokemonWebProject/pokemonWebProject/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using pokemonWebProject.DAL;
using pokemonWebProject.Models.pokemonModels;

namespace pokemonWebProject.Controllers
{
    public class TrainersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        // GET: Trainers
        public ActionResult Index()
        {
            var trainers = db.Trainers.Include(t => t.Person);
            return View(trainers.ToList());
        }

        // GET: Trainers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Include(p => p.Person).SingleOrDefault(x => x.TrainerID == id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // GET: Trainers/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.TrainerID = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Trainers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "TrainerID,CatchedPokemonsAmount,DexCompleteAmount,Allowance,PersonID")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {

                trainer.PersonID = trainer.TrainerID;
                db.Trainers.Add(trainer);

                if (UserManager.GetRoles(trainer.TrainerID) != null)
                { 
                    if (UserManager.GetRoles(trainer.TrainerID).Contains("Leader"))
                    {
                        Leader leader = db.Leaders.Find(trainer.TrainerID);
                        UserManager.RemoveFromRole(leader.LeaderID, "Leader");
                        db.Leaders.Remove(leader);
                    }

                    var challenge = db.Challenges.Where(x => x.CurrentLeaderID == trainer.TrainerID).ToList();
                    foreach (var ch in challenge)
                    {
                        db.Challenges.Remove(ch);
                    }

                }

                UserManager.AddToRole(trainer.TrainerID, "Trainer");

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TrainerID = new SelectList(db.Users, "Id", "FirstName", trainer.TrainerID);
            return View(trainer);
        }

        // GET: Trainers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = db.Trainers.Find(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            ViewBag.TrainerID = new SelectList(db.Users, "Id", "FirstName", trainer.TrainerID);
            return View(trainer);
        }

        // POST: Trainers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "TrainerID,CatchedPokemonsAmount,DexCompleteAmount,Allowance,PersonID")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TrainerID = new SelectList(db.Users, "Id", "FirstName", trainer.TrainerID);
            return View(trainer);
        }

        // GET: Trainers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Trainer trainer = db.Trainers.Include(p => p.Person).SingleOrDefault(x => x.TrainerID == id);

            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Trainer trainer = db.Trainers.Find(id);
            UserManager.RemoveFromRole(trainer.TrainerID, "Trainer");
            db.Trainers.Remove(trainer);

            // Remove all challnges connected
            var challenge = db.Challenges.Where(x => x.CurrentLeaderID == id).ToList();
            foreach (var ch in challenge)
            {
                db.Challenges.Remove(ch);
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

    }
}

pokemonWebProject/pokemonWebProject/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Bootstrap 4 Website Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>

        .fakeimg {
            height: 200px;
            background: #aaa;
        }
    </style>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"> </span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Użytkownicy", "Index", "ApplicationUsers", new { area = "" }, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1> PokeDex Application</h1>
        <p> Gotta catch'em all! </p>
    </div>


    @RenderBody()

    <div class="jumbotron text-center" style="margin-bottom:0">
        <p>@Html.Partial("_LoginPartial")</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

pokemonWebProject/pokemonWebProject/Views/Shared/PokeDexLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>PokeDex</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Content/half-slider.css" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#"> @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
            <a class="nav-item">@Html.Partial("_LoginPartial")</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                @if (!Request.IsAuthenticated)
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Lorem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Lorem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Lorem</a>
                        </li>
                    </ul>
                } else if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Użytkownicy", "Index", "ApplicationUsers", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Trenerzy", "Index", "Trainers", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Liderzy", "Index", "Leaders", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                } else if (Request.IsAuthenticated && User.IsInRole("Trainer"))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Liderzy", "Index", "Leaders", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                } else if (Request.IsAuthenticated && User.IsInRole("Leader"))
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                             @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Wyzwania", "Index", "Challenges", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <header>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('../../Content/Images/wallpaper1.png')">
            <div class="carousel-caption d-none d-md-block">
            </div>
          </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>
    <!-- Page Content -->
    <section class="py-5">
        <div class="container">
            @RenderBody()
        </div>
    </section>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <center>
            created by s13711 Marcin Krupa, project MAS
        </center>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

pokemonWebProject/pokemonWebProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>