pokemonWebProject/pokemonWebProject/Models/pokemonModels/Leader.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace pokemonWebProject.Models.pokemonModels
{
    public class Leader
    {
        [Key]
        public int LeaderID { get; set; }

        public string Specialisation { get; set; }

        public string SecondJob { get; set; }

        public decimal Sallary { get; set; }


        // one to many
        public ICollection<Challenge> Challenges { get; set; }

        // kompozycja
        public ApplicationUser Person { get; set; }
        public int PersonID { get; set; }

        // dynamic




    }
}

pokemonWebProject/pokemonWebProject/Controllers/ChallengesController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using pokemonWebProject.DAL;
using pokemonWebProject.Models.pokemonModels;

namespace pokemonWebProject.Controllers
{
    public class ChallengesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Challenges
        public ActionResult Index()
        {
            int parsedId = int.Parse(User.Identity.GetUserId());
            int currentUserId = db.Users.FirstOrDefault(x => x.Id == parsedId).Id;
            var challenges = db.Challenges.Include(c => c.CurrentLeader.Person).Include(c => c.CurrentTrainer.Person).ToList().Where(c => c.CurrentLeaderID == currentUserId);
            return View(challenges);
        }

        // GET: Challenges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            return View(challenge);
        }

        // GET: Challenges/CreateByTrainer/5
        [Authorize(Roles = "Trainer")]
        public ActionResult CreateByTrainer(int id)
        {
            Challenge challenge = new Challenge();
            challenge.CurrentLeaderID = id;

            return View(challenge);

        }

        // POST: Challenges/CreateByLeader
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainer")]
        public ActionResult CreateByTrainer([Bind(Include = "ChallengeID,ChallengeDate,Description,Result,AsAccepted,DeclineReasonTopic,DeclineReasonDescription,CurrentLeaderID,CurrentTrainerID")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                Challenge result = new Challenge
                {
                    ChallengeID = challenge.ChallengeID,
                    ChallengeDate = challenge.ChallengeDate,
                    CurrentTrainerID = getCurrentUser(),
                    CurrentLeaderID = challenge.CurrentLeaderID
                };

                db.Challenges.Add(result);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // GET: Challenges/Accept/5
        [Authorize(Roles = "Leader")]
        public ActionResult Accept(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // POST: Challenges/Accept/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Leader")]
        public ActionResult Accept([Bind(Include = "ChallengeID,ChallengeDate,Description,Result,AsAccepted,DeclineReasonTopic,DeclineReasonDescription,CurrentLeaderID,CurrentTrainerID")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                var result = new Challenge
                {
                    ChallengeID = challenge.ChallengeID,
                    ChallengeDate = challenge.ChallengeDate,
                    Result = challenge.Result,
                    Description = challenge.Description,
                    AsAccepted = true,
                    CurrentLeaderID = challenge.CurrentLeaderID,
                    CurrentTrainerID = challenge.CurrentTrainerID
                };

                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();

                sendAcceptInfoEmail(challenge.CurrentTrainerID);

                return RedirectToAction("Index");
            }

            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // GET: Challenges/Decline/5
        [Authorize(Roles = "Leader")]
        public ActionResult Decline(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Leader")]
        public ActionResult Decline([Bind(Include = "ChallengeID,ChallengeDate,Description,Result,AsAccepted,DeclineReasonTopic,DeclineReasonDescription,CurrentLeaderID,CurrentTrainerID")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                var result = new Challenge
                {
                    ChallengeID = challenge.ChallengeID,
                    ChallengeDate = challenge.ChallengeDate,
                    DeclineReasonTopic = challenge.DeclineReasonTopic,
                    DeclineReasonDescription = challenge.DeclineReasonDescription,
                    AsAccepted = false,
                    CurrentLeaderID = challenge.CurrentLeaderID,
                    CurrentTrainerID = challenge.CurrentTrainerID
                };

                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();

                sendDeclineInfoEmail(challenge.CurrentTrainerID);

                return RedirectToAction("Index");
            }

            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // GET: Challenges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // POST: Challenges/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChallengeID,ChallengeDate,Description,Result,AsAccepted,DeclineReasonTopic,DeclineReasonDescription,CurrentLeaderID,CurrentTrainerID")] Challenge challenge)
        {
            if (ModelState.IsValid)
            {
                db.Entry(challenge).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CurrentLeaderID = new SelectList(db.Leaders, "LeaderID", "Specialisation", challenge.CurrentLeaderID);
            ViewBag.CurrentTrainerID = new SelectList(db.Trainers, "TrainerID", "TrainerID", challenge.CurrentTrainerID);
            return View(challenge);
        }

        // GET: Challenges/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Challenge challenge = db.Challenges.Find(id);
            if (challenge == null)
            {
                return HttpNotFound();
            }
            return View(challenge);
        }

        // POST: Challenges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Challenge challenge = db.Challenges.Find(id);
            db.Challenges.Remove(challenge);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int getCurrentUser()
        {
            int currentUserId = int.Parse(User.Identity.GetUserId());
            var currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);

            return currentUser.Id;
        }

        private readonly static string mailClient = "app_mail@gmail.com";
        private readonly static string emailPassword = "password_to_mailClient";

        public void sendAcceptInfoEmail(int trainerID)
        {

pokemonWebProject/pokemonWebProject/Controllers/LeadersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using pokemonWebProject.DAL;
using pokemonWebProject.Models.pokemonModels;

namespace pokemonWebProject.Controllers
{
    public class LeadersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        // GET: Leaders
        [Authorize(Roles = "Admin, Trainer")]
        
        public ActionResult Index()
        {
            var leaders = db.Leaders.Include(l => l.Person);
            return View(leaders.ToList());
        }

        // GET: Leaders/Details/5
        [Authorize(Roles = "Admin, Trainer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Leader leader = db.Leaders.Include(p => p.Person).SingleOrDefault(x => x.LeaderID == id);
           
            if (leader == null)
            {
                return HttpNotFound();
            }
            return View(leader);
        }

        // GET: Leaders/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Leaders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "LeaderID,Specialisation,SecondJob,Sallary,PersonID")] Leader leader)
        {
            if (ModelState.IsValid)
            {
                db.Leaders.Add(leader);

                if (UserManager.GetRoles(leader.LeaderID) != null)
                {
                    if (UserManager.GetRoles(leader.LeaderID).Contains("Trainer"))
                    {
                        Trainer trainer = db.Trainers.Find(leader.LeaderID);
                        UserManager.RemoveFromRole(trainer.TrainerID, "Trainer");
                        db.Trainers.Remove(trainer);

                        var challenge = db.Challenges.Where(x => x.CurrentTrainerID == leader.LeaderID).ToList();
                        foreach (var ch in challenge)
                        {
                            db.Challenges.Remove(ch);
                        }
                    }
                }

                UserManager.AddToRole(leader.LeaderID, "Leader");

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // GET: Leaders/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leader leader = db.Leaders.Find(id);
            if (leader == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // POST: Leaders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "LeaderID,Specialisation,SecondJob,Sallary,PersonID")] Leader leader)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leader).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeaderID = new SelectList(db.Users, "Id", "FirstName", leader.LeaderID);
            return View(leader);
        }

        // GET: Leaders/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leader leader = db.Leaders.Include(p => p.Person).SingleOrDefault(x => x.LeaderID == id);

            if (leader == null)
            {
                return HttpNotFound();
            }
            return View(leader);
        }

        // POST: Leaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Leader leader = db.Leaders.Find(id);
            UserManager.RemoveFromRole(leader.LeaderID, "Leader");
            db.Leaders.Remove(leader);

            // Remove all challnges connected
            var challenge = db.Challenges.Where(x => x.CurrentTrainerID == id).ToList();
            foreach (var ch in challenge)
            {
                db.Challenges.Remove(ch);
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

    }
}

pokemonWebProject/pokemonWebProject/Views/Leaders/Create.cshtml
@model pokemonWebProject.Models.pokemonModels.Leader

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leader</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LeaderID, "LeaderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LeaderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LeaderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specialisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondJob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondJob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondJob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sallary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sallary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sallary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pokemonWebProject/pokemonWebProject/Views/Leaders/Delete.cshtml
@model pokemonWebProject.Models.pokemonModels.Leader

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specialisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specialisation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondJob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondJob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sallary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sallary)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

pokemonWebProject/pokemonWebProject/Views/Leaders/Details.cshtml
@model pokemonWebProject.Models.pokemonModels.Leader

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Leader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specialisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specialisation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecondJob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecondJob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sallary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sallary)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LeaderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

pokemonWebProject/pokemonWebProject/Views/Leaders/Edit.cshtml
@model pokemonWebProject.Models.pokemonModels.Leader

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leader</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LeaderID)

        <div class="form-group">
            @Html.LabelFor(model => model.Specialisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecondJob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecondJob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecondJob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sallary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sallary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sallary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pokemonWebProject/pokemonWebProject/Views/Leaders/Index.cshtml
@model IEnumerable<pokemonWebProject.Models.pokemonModels.Leader>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Specialisation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecondJob)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sallary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Person.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Specialisation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SecondJob)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sallary)
        </td>
        <td>

            @Html.ActionLink("Detale", "Details", new { id = item.LeaderID }) |
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edytuj", "Edit", new { id = item.LeaderID }) 
                @Html.ActionLink("Usuń", "Delete", new { id = item.LeaderID }) 
            }
            @if (Request.IsAuthenticated && User.IsInRole("Trainer"))
            {
                @Html.ActionLink("Rzuć Wyzwanie", "CreateByTrainer", "Challenges", new { id = item.LeaderID }, new { area = "" })
            }
        </td>
    </tr>
}

</table>